apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: smallcase-demo
  labels:
    app: flask
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
